### ISSUE TITLE
how to specify when projects have files with other licenses?

### ISSUE THREAD

**Issue by afeld** [18F/open-source-policy#36]
Came up in https://github.com/18F/C2/pull/288#issuecomment-89300694...we have an app that is almost all our code (CC0), but have a couple of vendor JS/CSS files checked in that have other licenses. What's the best way to specify this?

It looks like [some](https://github.com/18F/foia-hub/blob/master/LICENSE.md) [projects](https://github.com/cfpb/regulations-site/blob/master/TERMS.md#exceptions) list all the exceptions explicitly...would it be sufficient to say "CC0...except where otherwise specified at the top of the file"?

**Comment by adelevie** [comment]
IANAL

> would it be sufficient to say "CC0...except where otherwise specified at the top of the file"?

Probably yes, so long as the maintainer ensures those headers are present and up-to-date.

**Comment by konklone** [comment]
> It looks like some projects list all the exceptions explicitly...would it be sufficient to say "CC0...except where otherwise specified at the top of the file"?

Probably, maybe also point to the parent directory where those files can be found (e.g. `assets/`)?

**Comment by paultag** [comment]
That's usually what I do in a top level `LICENSE` file, if the project has
mixed licensing, and have something like `LICENSE.AGPL` or `LICENSE.Expat`
for the licenses required

On Fri, Apr 3, 2015 at 1:38 PM, Eric Mill <notifications@github.com> wrote:

> It looks like some projects list all the exceptions explicitly...would it
> be sufficient to say "CC0...except where otherwise specified at the top of
> the file"?
>
> Probably, maybe also point to the parent directory where those files can
> be found (e.g. assets/)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/open-source-policy/issues/36#issuecomment-89371350>
> .
>



-- 
:wq

**Comment by brittag** [comment]
Here's what I helped write the Draft US Web Design Standards: https://github.com/18F/web-design-standards#licenses-and-attribution - the README and LICENSE files list each of the reused files, their authors, and their licenses.

I went for maximum detail when listing the reused work because (1) it's friendly and polite to give clear credit to the authors, (2) it clearly shows that we reuse existing work when possible instead of making everything from scratch, (3) it's very helpful information for anyone who wants to reuse parts of the project and needs to be careful about licensing.

**Comment by konklone** [comment]
That's A+ writing and work, @brittag, thank you for doing and sharing that.

**Comment by afeld** [comment]
Recommendation for now is "send any licensing questions to the Office of General Counsel (OGC)."
