### ISSUE TITLE
This layout wasn't built and developed for my company

### ISSUE THREAD

**Issue by tranhelen** [18F/open-source-policy#37]
I created this layout that you are using for my company's Open Source page. While the page is listing Open Source projects and the code on the various project pages are open-source, the layout itself was meant to be only used for our company's work.

Additionally, just a note, when you're using work from a repo with an MIT license, it's supposed to be explicitly noted where the work came from. 

> The MIT License is a free software license originating at the Massachusetts Institute of Technology (MIT).[1] It is a permissive free software license, meaning that it permits reuse within proprietary software provided all copies of the licensed software include a copy of the MIT License terms and the copyright notice.

Can you please change your theme/template or at least credit Shopify for the design as stated in the license in the repo?

Thanks,
Helen

**Comment by gbinal** [comment]
Hi @tranhelen.  Thanks for reaching out and sorry for the trouble.  

I'm going to move this over to the issue tracker for https://github.com/18F/18f.github.io, since I believe 18f.github.io is the only place where this is happening.  We'll follow up shortly.

**Comment by tranhelen** [comment]
Nevermind, it looks to be resolved: https://twitter.com/konklone/status/601035063157985280

**Comment by konklone** [comment]
@tranhelen Thanks for raising this. It's not at all enjoyable to use people's work against their intent, even if the license issues are clear. In the meantime, @gbinal added some more explicit attribution in the footer of the website in https://github.com/18F/18f.github.io/pull/16.  We forked it because it was a beautiful starting point, but we haven't put much effort into the site since then, or promoted it widely. We'll definitely take Shopify's dissatisfaction into account as we figure out what to do.

If you don't want others to use the work, consider removing the MIT license, or updating the MIT license to clarify that it only covers code but not visual materials. Given the high % of public repos on GitHub that are openly licensed, if you do remove the license you may want to add an additional note that the repo is not intended to be used. It may be simpler to close the repo -- GitHub Pages will still host private repos.

**Comment by tranhelen** [comment]
Hey, cool thanks for putting that attribution in. I wasn't aware of the MIT license in the repo, all is good.
