### ISSUE TITLE
[Forge] Cannot walk when my mod is loaded

### ISSUE THREAD

**Issue by LyrasDerEchte** [18F/open-source-policy#48]
Hey folks,

I've got a very annoying problem / bug that I can't fix. I am creating a forge mod for somebody but every time I join onto a server or even play alone in singleplayer, I cannot move, open the inventory, click the mouse or similar. What my mod does at the moment is creating a button in the "GuiOptions"-gui and this one opens an own gui with some options for my mod.

Is my problem common? Or am I just stupid? :c

Thanks in advance

~ Lyras
PS: Im new to forge but I already know java ;)

**Comment by brittag** [comment]
Hi Lyras! Looking at your question, it sounds like you meant to ask this in a different place, since this is an issue tracker for discussion of 18F's open source policy and team practices. It's no problem for accidental questions to get posted here, we just aren't going to be able to help you find a solution to your problem here. :) I wish you well with finding an answer! I'll close this up for you.

**Comment by LyrasDerEchte** [comment]
In this moment I found a solution :D
