### ISSUE TITLE
add guidance about forking projects with non-public-domain licenses

### ISSUE THREAD

**Issue by afeld** [18F/open-source-policy#49]
Scenario: "I'm forking an MIT-licensed project for use at 18F...does that fork remain MIT-licensed, or are all contributions on that fork public domain on top of the existing code that's MIT-licensed, or...?"

I think the following from the MIT license pertains here:

> Permission to use, copy, modify, and/or distribute this software...provided that the above copyright notice and this permission notice appear in all copies.

**Comment by brittag** [comment]
Yes! We have a start on this in "List the licensing information for your project” on https://pages.18f.gov/open-source-guide/making-readmes-readable/

We could pull that out into its own page in the open source guide about licensing, and add various common licensing situations there.

**Comment by brittag** [comment]
We can also link to http://www.gnu.org/licenses/gpl-faq.en.html#GPLUSGovAdd as a helpfully authoritative reference about reusing GPL work in government.

**Comment by brittag** [comment]
Noting for myself that we see "what do I do if I want to fork a non-public-domain open source project" and "what do I do when I include non-public-domain open source resources within my project" fairly often at 18F - I've chatted about this with three people for three different projects this week.

Usually I point people to examples to explain how to write a complex LICENSE page, such as:

* https://github.com/18F/web-design-standards/blob/staging/LICENSE.md
* https://github.com/18F/retext-18f/blob/master/LICENSE.md
* https://github.com/cfpb/cfgov-refresh/blob/master/TERMS.md

I also end up explaining principles including:

* We can include or fork any project that has a standard open source license (including MIT, Apache v2, GPL, etc.), as long as we carefully comply with the license. Usually this includes writing a careful LICENSE file.
* The point of a LICENSE file is to help the reader understand what *they* are allowed to do with the repository. There no specific required format for a LICENSE file that explains a complex licensing situation - the point is to help humans understand what's going on, since humans are reading it.
* Use our standard LICENSE, CONTRIBUTING, and README files as a basis and modify them to fit the licensing situation.
* Somewhere in the repo (such as in those three files), we need to clearly communicate to the reader (who may be outside 18F) that their contributions to 18F repositories will be in the public domain. We usually do this with the CONTRIBUTING file - it's in the boilerplate there.

**Comment by afeld** [comment]
Closing as stale.
